name: Build JavaScript assets

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@master
            - uses: flarum/action-build@3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  commit_all_dirty: true
